# Sample config for local use

fetchers:
  config_dir: "./config/fetchers/"
host: "localhost"
port: 8080
db:
  host: "db"
  port: "5432"
  database: "cloud_mirror"
  user: "postgres"
  password: "postgres"
static_root_url: '/static'
secret_key: 'Thirty  two  length  bytes  key.'